version: "3.3"

volumes:
  data_db:

services:
  mysql:
    image: mysql:latest
    volumes:
      - data_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db